#!/usr/bin/env python
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from api.models import *

def main():
    user_1 = User(username='0911111111', password='1')
    user_1.save()
    user_2 = User(username='0922222222', password='2')
    user_2.save()
    Profile(user=user_1, phone_number=user_1.username).save()
    Profile(user=user_2, phone_number=user_2.username).save()

if __name__ == "__main__":
    main()
