#!/usr/bin/env python
from plate_server import settings
from django.core.management import setup_environ
setup_environ(settings)
import django.db.utils
from api.models import *
from django.contrib.auth.models import Group, User

# get_or_create won't raise any error if it's alread exist
# make sure the groups exist
vendor_group = Group.objects.get_or_create(name="vendor")
user_group = Group.objects.get_or_create(name="user")

# add 4 users and 2 vendors using new API
number_of_users = 4
for i in range(1, number_of_users+1):
    phone_number = '09' + str(i)*8

    user = User(username=phone_number, password=str(i))
    user.save()

    group = Group.objects.get(name="user")
    group.user_set.add(user)

    Profile(user=user, phone_number=phone_number).save()
    print 'User' + str(i) + '(' + phone_number + ') is created'

number_of_vendors = 2
for i in range(1, number_of_vendors+1):
    vendor = User(username='v'+str(i), password=str(i))
    vendor.save()

    group = Group.objects.get(name="vendor")
    group.user_set.add(vendor)

    Profile(user=vendor, phone_number='').save()
    print 'Vendor' + str(i) + ' is created'
